"""
Generate the precomputed wire map for the Vercel demo endpoint by running the REAL shipped
package (columna-core + columna-server) over the packaged demo Manifold.

Why precompute: the real engine needs polars+pyarrow+duckdb (~270MB unzipped) which exceeds
Vercel's 250MB serverless limit. So we capture genuine wire here (never a facsimile) and the
lightweight function serves it. The finite fool-it surface (a measure name templated into
"<name> @ store, day") plus the four seeded queries and the clarify round-trip is fully covered.

Honesty guarantees:
  * every wire object below is produced by T.query(...) — the exact Python API truth.
  * the unknown-column case is stored as a template; the function substitutes ONLY the user's
    own typed token into columns[0].name and the deterministic detail string
    ("unknown column '<token>'") — the engine's own formatting, not an invented result.

Run:  python scripts/generate.py   (from apps/demo-endpoint-vercel/, needs the dev venv)
Output: _wire/precomputed.json  (committed; regenerate on any package bump — drift-guarded by
        the recorded columna_core / columna_server versions in meta).
"""
from __future__ import annotations

import json
import os
from importlib.metadata import version

from columna_server import tools as T
from columna_server.demo import DEMO_MANIFOLD_ID, demo_store

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(HERE, "_wire", "precomputed.json")

# The fool-it template (must match apps/website seeded_queries.json foolIt.template).
FOOL_TEMPLATE = "%s @ store, day"
# What the demo manifold actually exposes (the "here is what this manifold has" index).
MEASURE_INDEX = ["revenue", "orders", "visitors", "level", "med_amount", "region_label"]

# The four seeded queries (must match seeded_queries.json).
SEEDED = [
    ("clarify", "sell_through_rate: revenue / level.last @ store, day", None),
    ("disclose", "revenue: revenue, inv: level.last @ region", None),
    ("refuse", "sell_through_rate: revenue / level.last @ store, day", "transactions"),
    ("serve", "revenue @ region", None),
]
WEDGE = "sell_through_rate: revenue / level.last @ store, day"


def key(frameql: str, universe):
    return f"{universe or ''}||{frameql.strip()}"


def main() -> int:
    store = demo_store()
    entries: dict[str, dict] = {}

    def capture(frameql, universe=None):
        wire = T.query(store, DEMO_MANIFOLD_ID, frameql, universe=universe)
        entries[key(frameql, universe)] = {"frameql": frameql, "universe": universe, "wire": wire}
        return wire

    # 1) seeded queries (also feeds the site's seed buttons if ever served live)
    for _id, fq, uni in SEEDED:
        capture(fq, uni)

    # 2) clarify round-trip: WEDGE pinned to each candidate universe the clarify surfaced
    clarify = entries[key(WEDGE, None)]["wire"]
    for col in clarify.get("columns", []):
        for alt in (col.get("no_result") or {}).get("alternatives", []):
            uni = (alt.get("apply") or {}).get("universe")
            if uni:
                capture(WEDGE, uni)

    # 3) fool-it: every real measure templated as "<name> @ store, day"
    for m in MEASURE_INDEX:
        capture(FOOL_TEMPLATE % m)

    # 4) unknown-column template (the honest refusal for any name not in the manifold)
    UNKNOWN_TOKEN = "_UNKNOWN_"  # a sentinel no real query can contain
    unknown_wire = T.query(store, DEMO_MANIFOLD_ID, FOOL_TEMPLATE % UNKNOWN_TOKEN)

    out = {
        "meta": {
            "note": "generated by running the shipped package; never hand-edited",
            "contract_version": T.CONTRACT_VERSION,
            "columna_core": version("columna-core"),
            "columna_server": version("columna-server"),
            "manifold": DEMO_MANIFOLD_ID,
            "fool_template": FOOL_TEMPLATE,
            "measure_index": MEASURE_INDEX,
        },
        "entries": entries,
        "unknown_template": {"token_sentinel": UNKNOWN_TOKEN, "wire": unknown_wire},
    }
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        json.dump(out, f, indent=2, ensure_ascii=False)
    print(f"wrote {OUT}: {len(entries)} exact entries + unknown template")
    for k, v in entries.items():
        print(f"  {v['wire']['outcome']:9} {k}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
