#!/usr/bin/env python3
"""
regen_examples.py — the Frame-QL manual's example regeneration harness (ADR-035 D4).

"The manual is structurally incapable of documenting a query it did not run." Every executable
example in a manual is a ```frameql block immediately followed by a ```frameql-output block. This
harness extracts each query, RUNS it against the shipped package over a fixture Manifold, formats the
outcome, and rewrites the output block. In --check mode (CI) it regenerates in memory and fails if any
example fails to parse/run OR if the regenerated output differs from what is committed — so an example
that stops parsing (or whose answer drifts) fails the manual's build.

Marking scheme (CP-M1 fork — proposed): fenced-block info strings.
    ```frameql
    SELECT revenue AT {region}
    ```
    ```frameql-output
    (machine-generated — do not edit by hand)
    ...
    ```
An `frameql` block with no following `frameql-output` block is an authoring error (flagged).

An example is a Frame-QL 1.0 ENVELOPE statement, and this harness has no grammar of its own: it calls
the shipped `columna_core.envelope.parse_statement` and the planner's statement path, which is what
every other surface calls. So an example this harness accepts is an example the product accepts —
the property the integrity rule rests on.
"""
from __future__ import annotations

import argparse
import glob
import os
import re
import sys

from columna_core import ManifoldServer, DuckDBConnector
from columna_core.envelope import parse_statement
from columna_core.parser import parse_manifold
from columna_core.disclosure_wire import wire_frame

_HERE = os.path.dirname(os.path.abspath(__file__))
_DO_NOT_EDIT = "# machine-generated by docs/tools/regen_examples.py — do not edit by hand"

# ── the docs fixture Manifold + data (a small `finance` Manifold the examples run against) ──────
# A CP-M1 fork: reuse the shipped demo Manifold vs a docs-local fixture. Proposed: a docs-local
# fixture, so the manual's examples keep their readable `finance`/`revenue`/`cost` vocabulary while
# staying executable and independent of demo-data changes.
_FINANCE_CML = """
MANIFOLD finance VERSION 1
UNIVERSE transactions = customer * day
LEVEL customer = customer_id BASE
LEVEL day      = day         BASE
LEVEL region   = region
HIERARCHY cust_geo { customer -> region VIA customers(customer_id, region) }
MEASURE revenue ON transactions FROM txns AS sum(amount)
MEASURE cost    ON transactions FROM txns AS sum(cost_amount)
"""

_TXNS = [  # (customer_id, day, amount, cost_amount)
    ("c1", "2024-01-01", 100.0, 60.0), ("c1", "2024-01-02", 140.0, 80.0),
    ("c2", "2024-01-01", 200.0, 130.0), ("c2", "2024-01-03", 60.0, 40.0),
    ("c3", "2024-01-02", 300.0, 210.0),
]
_CUSTOMERS = [("c1", "east"), ("c2", "east"), ("c3", "west")]


def _fixture_server():
    import duckdb
    con = duckdb.connect()
    con.execute("CREATE TABLE txns(customer_id VARCHAR, day VARCHAR, amount DOUBLE, cost_amount DOUBLE)")
    con.executemany("INSERT INTO txns VALUES (?,?,?,?)", _TXNS)
    con.execute("CREATE TABLE customers(customer_id VARCHAR, region VARCHAR)")
    con.executemany("INSERT INTO customers VALUES (?,?)", _CUSTOMERS)
    srv = ManifoldServer(parse_manifold(_FINANCE_CML), DuckDBConnector(con))
    # P0.5a closed-by-default serving: transport across an FD-claimed edge serves only once
    # adjudication positively admits it. A documentation harness that exercises governed serving
    # must enter the SAME publication/admission lifecycle the product requires — `publish()` is
    # that lifecycle (adjudicate strictly, then build witnesses), not a docs-only bypass. Without
    # it these examples document the behaviour of an unpublished manifold, which is not the
    # behaviour being documented.
    srv.publish()
    return srv


# ── run one statement, format its outcome as the committed output block body ─────────────────────
def run_query(server, query: str) -> str:
    stmt = parse_statement(query)                       # the envelope grammar — the language
    fr = server.planner.run_statement(stmt)             # the whole clause set, one call
    w = wire_frame(fr)
    lines = [_DO_NOT_EDIT, f"outcome: {w['outcome']}"]
    if fr.data is not None:
        cols = fr.data.columns
        # A committed block needs a settled row order, and the output anchor gives one. Where the
        # statement writes its own ORDER BY the planner has already applied it — sorting again would
        # overwrite the very thing that example documents. The grand-total frame (`AT {}`) has one row
        # and no coordinate to sort on.
        data = fr.data if (stmt.order_by or not stmt.anchor) else fr.data.sort(list(stmt.anchor))
        lines.append(" | ".join(cols))
        lines.append(" | ".join("-" * len(c) for c in cols))
        for row in data.iter_rows(named=True):
            lines.append(" | ".join(_fmt(row[c]) for c in cols))
    for col in w.get("columns", []):
        for d in col.get("disclosures") or []:
            lines.append(f"# disclosure[{col['name']}]: {d['code']} ({d['materiality']})")
        nr = col.get("no_result")
        if nr:
            lines.append(f"# {col['name']}: {nr.get('reason')} — {nr.get('detail', '')}")
    return "\n".join(lines)


def _fmt(v):
    if isinstance(v, float):
        return f"{v:.4g}"
    return str(v)


# ── block extraction / rewrite ──────────────────────────────────────────────────────────────────
_BLOCK_RE = re.compile(
    r"```frameql\n(?P<query>.*?)\n```\n+```frameql-output\n(?P<out>.*?)\n```",
    re.DOTALL,
)


def regenerate(text: str, server) -> tuple[str, int, list]:
    """Return (new_text, n_examples, errors). Rewrites every frameql-output block from its query."""
    errors = []
    count = 0

    def _sub(m):
        nonlocal count
        count += 1
        query = m.group("query").strip()
        try:
            body = run_query(server, query)
        except Exception as e:                             # a failing example fails the build
            errors.append((query, f"{type(e).__name__}: {e}"))
            body = m.group("out")                          # leave prior body; error is reported
        return f"```frameql\n{query}\n```\n\n```frameql-output\n{body}\n```"

    new_text = _BLOCK_RE.sub(_sub, text)
    # an frameql block with no following output block is an authoring error
    lone = len(re.findall(r"```frameql\n", text)) - count
    if lone > 0:
        errors.append(("<structure>", f"{lone} `frameql` block(s) have no following `frameql-output` block"))
    return new_text, count, errors


def main():
    ap = argparse.ArgumentParser(description="Regenerate Frame-QL manual example outputs by execution.")
    ap.add_argument("paths", nargs="*", default=None, help="markdown files (default: docs/*.md)")
    ap.add_argument("--check", action="store_true", help="CI mode: fail on any run error or output drift")
    args = ap.parse_args()

    paths = args.paths or sorted(glob.glob(os.path.join(_HERE, "..", "**", "*.md"), recursive=True))
    server = _fixture_server()
    total, drift, failed = 0, [], []
    for path in paths:
        with open(path) as f:
            text = f.read()
        if "```frameql\n" not in text:
            continue
        new_text, n, errors = regenerate(text, server)
        total += n
        for q, e in errors:
            failed.append((path, q, e))
        if new_text != text:
            drift.append(path)
            if not args.check:
                with open(path, "w") as f:
                    f.write(new_text)

    print(f"examples: {total} across {len(paths)} file(s); errors: {len(failed)}; drift: {len(drift)}")
    for path, q, e in failed:
        print(f"  FAIL {os.path.basename(path)}: {q!r} -> {e}")
    if args.check:
        for path in drift:
            print(f"  DRIFT {os.path.basename(path)}: committed output != regenerated (run without --check)")
        if failed or drift:
            sys.exit(1)
    elif failed:
        sys.exit(1)


if __name__ == "__main__":
    main()
