#!/usr/bin/env python3
"""
regen_capability_tables.py — the capability tables are PROJECTIONS, not documents.

THE P0-17 CLASS, CLOSED. Eight reducer rows were adjudicated [ROADMAP] in the Reference Manual; that
ruling's repair scope was `/docs/reference` only; and the Frame-QL Manual carried the contradicting
claim until a gate went looking, because nothing coupled the two. Hand-propagation between manuals is
not a discipline problem, it is a missing edge — so the tables stop being authored.

    canonical standing   specs/frameql_capabilities.toml   AUTHORED
    profile standing     specs/profiles/*.toml             AUTHORED
    build realization    the installed package             MEASURED
            |
            +-> this generator -> the capability tables in every manual

Each manual keeps its own PROSE; only the mechanical restatement of a finite registry is generated.
That is the narrow rule (ruled Huayin, 2026-09-01): prose that mechanically restates a finite
normative rule or registry must be generated from its authority or conformance-checked against it.
Ordinary explanatory prose is untouched, and no general "law registry" is invented.

Run:  python docs/tools/regen_capability_tables.py [--check]
      --check regenerates in memory and fails if a committed table has drifted.
"""
from __future__ import annotations
import argparse
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import capability_authority as A                                # noqa: E402

_DOCS = pathlib.Path(__file__).resolve().parents[1]
BEGIN = "<!-- BEGIN GENERATED: capability-reference -->"
END = "<!-- END GENERATED: capability-reference -->"

#: which manuals carry the projection. Each gets the SAME table from the SAME authority — that
#: identity is the point, and is what makes a second hand-maintained matrix impossible to sustain.
#: EACH DOCUMENT GETS THE PROJECTION ITS JURISDICTION OWNS, and only that one. The combined
#: three-column table was itself a small version of the conflation this split exists to end: it put
#: canonical standing, an authored contract and a measured build in one grid, so a reader could not
#: tell which column was law, which was a promise, and which was an observation.
#:
#:   frame_ql_language.md      canonical standing only    — what the LANGUAGE has ruled in
#:   core_profile.md           the Core contract          — what a conforming Core UNDERTAKES
#:   platform_profile.md       additions over Core        — currently none
#:   frame_ql_build_status.md  the measured build         — plus conformance / lag / exceed
TARGETS = {
    "frame_ql_language.md": "canonical",
    "core_profile.md": "core_contract",
    "platform_profile.md": "platform_adds",
    "frame_ql_build_status.md": "build",
}

_LEVEL = {"execute": "executes", "plan": "plans only", "none": "\u2014"}

_NOTE = ("<!-- machine-generated by docs/tools/regen_capability_tables.py — do not edit by hand.\n"
         "     Edit the authority (specs/frameql_capabilities.toml, specs/profiles/*.toml), not this table. -->")


def _grid(header, rows):
    if not rows:
        return "_(none)_\n"
    return ("| " + " | ".join(header) + " |\n"
            + "|" + "|".join("---" for _ in header) + "|\n"
            + "".join("| " + " | ".join(r) + " |\n" for r in rows))


def _by_category(caps, category, position=None):
    for cid, c in sorted(caps.items()):
        if c["category"] != category:
            continue
        if position and c["position"] != position:
            continue
        if position is None and c["position"] == "predicate":
            continue
        yield cid, c


_SECTIONS = [("Reducers", "reducer", None), ("Maps — series position", "map", "series"),
             ("Predicate position", "map", "predicate"), ("Scans", "scan", None)]


def _sp(c, cid):
    return ", ".join(f"`{s}`" for s in c.get("spellings", [cid]))


def render(kind: str) -> str:
    caps = A.canonical_capabilities()
    core = A.profile("core")
    built = A.measure_build(caps)
    parts = [BEGIN, "", _NOTE, ""]

    if kind == "canonical":
        parts += ["Standing is what the language has ruled in — not what any build runs. "
                  "`ratified` means the construct is part of Frame-QL. `proposed` means it is "
                  "documented as language the envelope grows into, and has not been ruled in "
                  "(ADR-035 D1). What runs today is a separate question, answered in the build "
                  "status document.", ""]
        for title, cat, pos in _SECTIONS:
            rows = [(_sp(c, cid), c["standing"]) for cid, c in _by_category(caps, cat, pos)]
            parts += [f"### {title}", "", _grid(["Capability", "Canonical standing"], rows)]

    elif kind == "core_contract":
        parts += ["What a conforming Core implementation undertakes to realize. This is a promise, "
                  "not a measurement: what the shipped build actually does is in the build status "
                  "document, and it may conform, lag, or exceed what is written here.", ""]
        for title, cat, pos in _SECTIONS:
            rows = [(_sp(c, cid), _LEVEL[core.get(cid, "none")])
                    for cid, c in _by_category(caps, cat, pos) if core.get(cid, "none") != "none"]
            parts += [f"### {title}", "", _grid(["Capability", "Core undertakes"], rows)]

    elif kind == "platform_adds":
        adds = A.profile_additions("platform")
        rows = [(f"`{cid}`", _LEVEL[lv]) for cid, lv in sorted(adds.items())]
        parts += ["Frame-QL capabilities the Platform Profile realizes **beyond Core**. Platform "
                  "extends Core, so it also undertakes everything in the Core contract.", "",
                  _grid(["Capability", "Platform adds"], rows)]

    elif kind == "build":
        try:
            from importlib.metadata import version
            ver = version("columna-core")
        except Exception:                                      # pragma: no cover
            ver = "unknown"
        deltas = {d[0]: d for d in A.build_deltas(caps, core, built)}
        exceeded = A.standing_exceeded(caps, core, built)
        parts += [f"Measured from the installed `columna-core` **{ver}**. Nothing here is authored: "
                  "each row is read from the shipped package. A build may conform to, lag, or "
                  "exceed the Core contract; it never changes it.", ""]
        for title, cat, pos in _SECTIONS:
            rows = []
            for cid, c in _by_category(caps, cat, pos):
                b, u = built.get(cid, "none"), core.get(cid, "none")
                if b == "none" and u == "none":
                    continue
                d = deltas.get(cid)
                rows.append((_sp(c, cid), _LEVEL[u], _LEVEL[b],
                             d[3] if d else "conforms"))
            parts += [f"### {title}", "",
                      _grid(["Capability", "Core undertakes", "This build", "Conformance"], rows)]
        parts += ["### Realization ahead of canonical standing", "",
                  "These run, or are undertaken, while the language has **not** ratified them. That "
                  "is a legitimate state and it is listed rather than hidden: a build does not "
                  "promote a construct into the language by running it, and a profile does not make "
                  "a proposed construct ratified by undertaking it. Ratification is a separate "
                  "review of the construct itself.", "",
                  _grid(["Capability", "Canonical standing", "Core undertakes", "This build"],
                        [(f"`{cid}`", "proposed", _LEVEL[pl], _LEVEL[bl]) for cid, pl, bl in exceeded])]

    parts.append(END)
    return "\n".join(parts)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    drift, missing = [], []
    for name, kind in TARGETS.items():
        block = render(kind)
        path = _DOCS / name
        if not path.exists():
            continue
        text = path.read_text()
        if BEGIN not in text or END not in text:
            missing.append(name)
            continue
        new = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), lambda _m: block, text, flags=re.S)
        if new != text:
            drift.append(name)
            if not args.check:
                path.write_text(new)
    # AN ORPHANED PROJECTION IS THE FAILURE THIS TOOL EXISTS TO PREVENT. A document carrying the
    # generated markers while NOT being a target would hold a copy nothing regenerates — a stale
    # second authority, arrived at by deletion rather than by hand. Caught here rather than trusted
    # to review; it already happened once, to the Reference Manual, within an hour of the split.
    for path in sorted(_DOCS.glob("*.md")):
        if path.name in TARGETS:
            continue
        if BEGIN in path.read_text():
            missing.append(f"{path.name} (ORPHAN: carries the generated block but is not a target — "
                           f"nothing regenerates it)")

    for name in missing:
        if "ORPHAN" in name:
            print(f"  {name}", file=sys.stderr)
        else:
            print(f"  {name}: no generated-capability block — add the BEGIN/END markers",
                  file=sys.stderr)
    if args.check and drift:
        for name in drift:
            print(f"  DRIFT {name}: the committed capability table differs from the authority",
                  file=sys.stderr)
    n = len(A.canonical_capabilities())
    print(f"capability tables: {n} capabilities projected into {len(TARGETS)} document(s); "
          f"{len(drift)} drifted, {len(missing)} missing the block")
    return 1 if (missing or (args.check and drift)) else 0


if __name__ == "__main__":
    sys.exit(main())
