#!/usr/bin/env python3
"""
regen_capability_tables.py — the capability tables are PROJECTIONS, not documents.

THE P0-17 CLASS, CLOSED. Eight reducer rows were adjudicated [ROADMAP] in the Reference Manual; that
ruling's repair scope was `/docs/reference` only; and the Frame-QL Manual carried the contradicting
claim until a gate went looking, because nothing coupled the two. Hand-propagation between manuals is
not a discipline problem, it is a missing edge — so the tables stop being authored.

    canonical standing   specs/frameql_capabilities.toml   AUTHORED
    profile standing     specs/profiles/*.toml             AUTHORED
    build realization    the installed package             MEASURED
            |
            +-> this generator -> the capability tables in every manual

Each manual keeps its own PROSE; only the mechanical restatement of a finite registry is generated.
That is the narrow rule (ruled Huayin, 2026-09-01): prose that mechanically restates a finite
normative rule or registry must be generated from its authority or conformance-checked against it.
Ordinary explanatory prose is untouched, and no general "law registry" is invented.

Run:  python docs/tools/regen_capability_tables.py [--check]
      --check regenerates in memory and fails if a committed table has drifted.
"""
from __future__ import annotations
import argparse
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import capability_authority as A                                # noqa: E402

_DOCS = pathlib.Path(__file__).resolve().parents[1]
BEGIN = "<!-- BEGIN GENERATED: capability-reference -->"
END = "<!-- END GENERATED: capability-reference -->"

#: which manuals carry the projection. Each gets the SAME table from the SAME authority — that
#: identity is the point, and is what makes a second hand-maintained matrix impossible to sustain.
TARGETS = ["frame_ql_manual_v2.md", "columna_reference_manual_5e.md"]

_STANDING = {"ratified": "ratified", "proposed": "proposed", "retired": "retired"}
_LEVEL = {"execute": "executes", "plan": "plans only", "none": "—"}


def _rows(caps, core, built, category, position=None):
    out = []
    for cid, c in sorted(caps.items()):
        if c["category"] != category:
            continue
        if position and c["position"] != position:
            continue
        if position is None and c["position"] == "predicate":
            continue
        spellings = ", ".join(f"`{s}`" for s in c.get("spellings", [cid]))
        out.append((spellings, _STANDING[c["standing"]],
                    _LEVEL[core.get(cid, "none")], _LEVEL[built.get(cid, "none")]))
    return out


def _table(rows):
    if not rows:
        return "_(none)_\n"
    head = ("| Capability | Canonical standing | Core Profile | This build |\n"
            "|---|---|---|---|\n")
    return head + "".join(f"| {a} | {b} | {c} | {d} |\n" for a, b, c, d in rows)


def render() -> str:
    caps = A.canonical_capabilities()
    core = A.profile("core")
    built = A.measure_build(caps)
    try:
        from importlib.metadata import version
        ver = version("columna-core")
    except Exception:                                          # pragma: no cover
        ver = "unknown"

    p = [BEGIN,
         "",
         "<!-- machine-generated by docs/tools/regen_capability_tables.py — do not edit by hand.",
         "     Canonical standing comes from specs/frameql_capabilities.toml; Core Profile from",
         "     specs/profiles/core_profile.toml; the build column is MEASURED from the installed",
         "     package. Edit the authority, not this table. -->",
         "",
         "**Two axes, never one.** *Canonical standing* is what the language has ruled in "
         "(ADR-035 D1: the grammar grows by ruling). *Core Profile* is what a conforming "
         "implementation undertakes to realize. *This build* is measured from the installed "
         f"`columna-core` ({ver}). A profile may add realization capability; it may not change what "
         "canonical Frame-QL means. A build may conform to, lag, or exceed a profile; it does not "
         "redefine it.",
         "",
         "### Reducers", "", _table(_rows(caps, core, built, "reducer")),
         "### Maps — series position", "", _table(_rows(caps, core, built, "map", "series")),
         "### Predicate position", "",
         "A canonical vocabulary governed by **syntax position**: these are usable in `WHERE` / "
         "`HAVING` and are not series-expression operators.",
         "", _table(_rows(caps, core, built, "map", "predicate")),
         "### Scans", "", _table(_rows(caps, core, built, "scan")),
         END]
    return "\n".join(p)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    block = render()
    drift, missing = [], []
    for name in TARGETS:
        path = _DOCS / name
        if not path.exists():
            continue
        text = path.read_text()
        if BEGIN not in text or END not in text:
            missing.append(name)
            continue
        new = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), lambda _m: block, text, flags=re.S)
        if new != text:
            drift.append(name)
            if not args.check:
                path.write_text(new)
    for name in missing:
        print(f"  {name}: no generated-capability block — add the BEGIN/END markers", file=sys.stderr)
    if args.check and drift:
        for name in drift:
            print(f"  DRIFT {name}: the committed capability table differs from the authority",
                  file=sys.stderr)
    n = len(A.canonical_capabilities())
    print(f"capability tables: {n} capabilities projected into {len(TARGETS)} manual(s); "
          f"{len(drift)} drifted, {len(missing)} missing the block")
    return 1 if (missing or (args.check and drift)) else 0


if __name__ == "__main__":
    sys.exit(main())
