"""What an Ask answer's standing IS, and the exact words the reader is shown.

Kept in one module because these strings are a promise to a reader, not UI copy. They say what
datumwise has and has not put its name to, and they must read identically wherever they appear —
the service, the site, the review screen. A promise that is phrased three ways is three promises.

TWO STANDINGS, AND THE GAP BETWEEN THEM IS THE POINT (Huayin, 2026-08-26):

  PROVISIONAL  a fresh answer. Generated. Cited. Not reviewed, not approved, not a datumwise
               publication. It may reason broadly, use public knowledge, and compare datumwise with
               the wider world — and precisely because it may do all that, it cannot be allowed to
               look like something datumwise has ratified.

  REVIEWED     an answer a human at datumwise approved for publication, on a date. This is the only
               standing that earns a public reputation: views, ratings, stars, ranking.

The notice is NOT to be tucked into an about page or a terms link. A reader who sees the answer
must see its standing in the same glance.
"""

from __future__ import annotations

import time

PROVISIONAL = "provisional"
REVIEWED = "reviewed"

PROVISIONAL_LABEL = "Provisional answer · not reviewed by datumwise"
PROVISIONAL_DETAIL = (
    "Generated by Ask from the cited datumwise sources. It may include Ask's own analysis and "
    "external research. It has not been reviewed or approved by datumwise, and it is not a "
    "datumwise publication."
)

REVIEWED_LABEL = "Reviewed by datumwise"
REVIEWED_DETAIL = (
    "A datumwise reviewer approved this answer for publication on this date. The datumwise-position "
    "claims in it are supported by the Core set."
)


def notice(standing: str, reviewed_at: float | None = None) -> dict:
    """The standing block an interface renders. One shape for both, so neither can be omitted."""
    if standing == REVIEWED:
        date = time.strftime("%-d %B %Y", time.gmtime(reviewed_at or time.time()))
        return {"standing": REVIEWED, "label": f"{REVIEWED_LABEL} · {date}",
                "detail": REVIEWED_DETAIL, "reviewedAt": reviewed_at}
    return {"standing": PROVISIONAL, "label": PROVISIONAL_LABEL, "detail": PROVISIONAL_DETAIL,
            "reviewedAt": None}
